[package]
name = "automaton-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tungstenite = "0.14"
serde_json = "1.0"
float-cmp = "0.9"
